# put this under /etc/ssh/sshd_config.d/

PasswordAuthentication no
KbdInteractiveAuthentication no
PermitEmptyPasswords no
PubkeyAuthentication yes
AuthorizedKeysFile .ssh/authorized_keys

Match User root
	AuthorizedKeysCommand /etc/ssh/sshd_auth.sh
	AuthorizedKeysCommandUser nobody
